### ISSUE TITLE
【测试指标低】

### ISSUE THREAD

**Issue by superwj1990** [maple-research-lab/AdCo#1]
你好，我用我自己的数据训练，发现 top1 ACC有99%的准确率，好像负样本没有起作用。增大了负样本学习率也没有改变。这个训练有什么技巧或注意的吗？

**Comment by WoodwindHu** [comment]
如果正负样本对抗起来的话 top1 ACC应该不会那么高，我们训练的时候大概八九十的样子，你可以试试调整mem_t这个参数，是用来控制负样本这边contrastive loss的temperature的，网络对temperature比学习率更敏感一些

**Comment by superwj1990** [comment]
好的，感谢回复。另外我想问一下，这个方案有在识别任务上试过吗，效果如何?

**Comment by wang3702** [comment]
你好，我们文章中已经提到，我们现在imagenet上pretrain然后在作为pretrained model在下游识别任务上做了测试。您可以看我们论文的downstream task的table

**Comment by Mhttx2016** [comment]
> 你好，我用我自己的数据训练，发现 top1 ACC有99%的准确率，好像负样本没有起作用。增大了负样本学习率也没有改变。这个训练有什么技巧或注意的吗？

我遇到和你同样的问题（top1 ACC有99%的准确率），请问你后来是怎么解决的
