### ISSUE TITLE
Feature dimension

### ISSUE THREAD

**Issue by lzyhha** [maple-research-lab/AdCo#11]
According to the paper, "the output feature map from the top ResNet-50 block is average-pooled and projects to a 128-D feature vector through two-layer". However, it seems that the feature dimension in the checkpoint is 256?

When I load the full model with fc, I get the message: "size mismatch for encoder_q.fc.2.weight: copying a param with shape torch.Size([256, 2048]) from checkpoint, the shape in current model is torch.Size([128, 2048])".

I used the checkpoint_70.6.pth.tar.
Maybe I got it wrong, can you answer my question?

**Comment by WoodwindHu** [comment]
Thank you for the question. It's our mistake that upload the wrong 256-D checkpoint. Sorry for bothering you with this mistake. Run the release code with 128-D would get the same result.

**Comment by lzyhha** [comment]
The cost of training a model on ImageNe-1k is relatively large. So can you release the pretrained model with 128D?

**Comment by wang3702** [comment]
Really sorry that we also did not have enough computation resources on our side. If you are using it for downstream tasks, I think you can simply remove the MLP head and load the ResNet encoder weights for your purposes. If you need to use it for self-supervised learning, I think you can directly train AdCo on your side.

**Comment by lzyhha** [comment]
May I ask whether the results in the README and paper are obtained with 128-D or 256-D?

**Comment by wang3702** [comment]
it's obtained by 128-D. You can download other models for a check. The symmetrical model is trained after our paper is submitted. Hence we made a small mistake when uploading the model.
