### ISSUE TITLE
关于对比工作mochi的问题

### ISSUE THREAD

**Issue by dumpling-Eric** [maple-research-lab/AdCo#16]
看到AdCo和MoCHi做了对比，但是MoCHi的原作者只开源了预训练模型，没有开源源码。看到作者对于MoCHi的超参也进行了调整，所以想问一下作者是否实现了MoCHi呢，可以分享一下源码吗

**Comment by wang3702** [comment]
您好，谢谢关注我们的工作。我们没有跑过mochi，我们用的他文章中报的相关metric
