### ISSUE TITLE
How long does the training take？

### ISSUE THREAD

**Issue by wanmeiziyoulan** [maple-research-lab/AdCo#7]
Hi，I found in the paper that it takes 2.26 hours to train a epoch, so does it take 18 days to train 200 epochs？But it only takes 53 hours for MoCov2 to train 200 epochs. 
Looking forward to your answer！

**Comment by wang3702** [comment]
That is GPU hour. Considering the typical setting is with 8 GPUs (both MoCo and AdCo). Thus the running time of the program should be 2.26*200/8 = 56.5 hours. It's almost the same running speed as MoCo.

**Comment by wanmeiziyoulan** [comment]
OK，thanks！
